plugins {
    id 'com.android.application'
}

android {
    namespace 'dk.oddfellow.slagelse.infotavle'
    compileSdk 35

    defaultConfig {
        applicationId "dk.oddfellow.slagelse.infotavle"
        minSdk 21
        targetSdk 28
        versionCode Integer.parseInt(System.getenv("GITHUB_RUN_NUMBER") ?: "1")
        versionName "1.0.${System.getenv("GITHUB_RUN_NUMBER") ?: "1"}"
    }
}

dependencies {
}
